id: IC9093DA9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T14:38:30+00:00'
last_modified: '2022-06-07T13:39:19.573645+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20574
  title: དམིགས་ཚད་སློབ་ཁྲིད་ཀྱི་རྨང་གཞིའི་ཤེས་བྱ་ཚངས་པའི་ཐིག་གི་སྤུན་ཟླ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    300E:
      image_group_id: I1KG23296
      title: ''
      total_pages: 142
      order: 1
      base_file: 300E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
