id: P000760
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20574
  title: དམིགས་ཚད་སློབ་ཁྲིད་ཀྱི་རྨང་གཞིའི་ཤེས་བྱ་ཚངས་པའི་ཐིག་གི་སྤུན་ཟླ།
  author: ''
  volumes:
    8de118c96f434b2e8ce3583689778de3:
      image_group_id: I1KG23296
      title: ''
      volume_number: 1
      total_pages: 142
      base_file: v001.txt
